// First-run seed — ported VERBATIM from family-shopping-app. Only used if the
// household has zero recipe records (fresh start). The real path for the merge
// is scripts/migrate-pantry.js, which brings the live data over.

export const SEED_RECIPES = [
  { name: "Balsamic Pork Medallions", url: "https://www.nourish-and-fete.com/wprm_print/balsamic-pork-tenderloin-medallions", category: "Pork", ingredients: [{name:"Pork Tenderloin",quantity:"1 lb"},{name:"Thyme",quantity:""},{name:"Rosemary",quantity:""},{name:"Sweet Paprika",quantity:"1 tsp"},{name:"Garlic Powder",quantity:"1 tsp"},{name:"Butter",quantity:"2 tbsp"},{name:"Chicken Broth",quantity:"1 cup"},{name:"Balsamic Vinaigrette",quantity:"3 tbsp"}] },
  { name: "Beef Stew", url: "https://thecozycook.com/slow-cooker-beef-stew/", category: "Other", ingredients: [{name:"Beef Broth",quantity:"4 cups"},{name:"Beef Roast",quantity:"2 lbs"},{name:"Potatoes",quantity:""},{name:"Carrots",quantity:""},{name:"Celery",quantity:""},{name:"Onion",quantity:"1"},{name:"Cabernet Sauvignon",quantity:"1 cup"},{name:"Beef Bouillon Cubes",quantity:"2"},{name:"Worcestershire Sauce",quantity:"2 tbsp"},{name:"Tomato Paste",quantity:"2 tbsp"},{name:"Bay leaves",quantity:"2"},{name:"Corn Starch",quantity:"2 tbsp"}] },
  { name: "Birria", url: "", category: "Other", ingredients: [] },
  { name: "Calzones", url: "", category: "Other", ingredients: [] },
  { name: "Chicken Alfredo", url: "", category: "Chicken", ingredients: [] },
  { name: "Chicken Parm", url: "", category: "Chicken", ingredients: [{name:"Chicken",quantity:"2 lbs"},{name:"Pasta Sauce",quantity:"1 jar"},{name:"Parmesan",quantity:"1 cup"},{name:"Mozzarella",quantity:"2 cups"}] },
  { name: "Dutch Oven Chicken", url: "https://biteswithbri.com/wprm_print/dutch-oven-chicken-breast", category: "Chicken", ingredients: [{name:"Butter",quantity:"3 tbsp"},{name:"Garlic",quantity:"4 cloves"},{name:"Thyme",quantity:""},{name:"Sage",quantity:""},{name:"Rosemary",quantity:""},{name:"Lemon",quantity:"1"},{name:"Chicken",quantity:"2 lbs"},{name:"Onion",quantity:"1"},{name:"White Wine",quantity:"1/2 cup"},{name:"Flour",quantity:"2 tbsp"},{name:"Chicken Broth",quantity:"1 cup"}] },
  { name: "Flatbread Pizza", url: "", category: "Other", ingredients: [{name:"Flatbread",quantity:""},{name:"Marinara",quantity:"1 cup"},{name:"Shredded Cheese",quantity:"2 cups"},{name:"Mozzarella",quantity:""},{name:"Pepperoni",quantity:""}] },
  { name: "Garlic Chicken", url: "https://simplehomeedit.com/recipe/creamy-garlic-chicken/", category: "Chicken", ingredients: [{name:"Chicken",quantity:"2 lbs"},{name:"Paprika",quantity:"1 tsp"},{name:"Onion Powder",quantity:"1 tsp"},{name:"Thyme",quantity:""},{name:"Flour",quantity:"2 tbsp"},{name:"Butter",quantity:"2 tbsp"},{name:"Minced Garlic",quantity:"4 cloves"},{name:"Chicken Stock",quantity:"1 cup"},{name:"Heavy Cream",quantity:"1/2 cup"},{name:"Dijon Mustard",quantity:"1 tbsp"},{name:"Parmesan",quantity:"1/2 cup"},{name:"Potatoes",quantity:""}] },
  { name: "Ham & Cheese Sliders", url: "https://www.allrecipes.com/recipe/216756/baked-ham-and-cheese-party-sandwiches/", category: "Sandwich", ingredients: [{name:"Butter",quantity:"1/2 cup"},{name:"Dijon Mustard",quantity:"2 tbsp"},{name:"Worcestershire Sauce",quantity:"1 tbsp"},{name:"Poppy Seeds",quantity:"1 tbsp"},{name:"Sandwhich Pickles",quantity:""},{name:"Hawaiian Rolls",quantity:"1 pack"},{name:"Deli Ham",quantity:"1 lb"},{name:"Cheddar Cheese",quantity:"1 lb"}] },
  { name: "Kielbasa & Rice", url: "", category: "Other", ingredients: [{name:"Kielbasa",quantity:"1 lb"},{name:"Chicken Rice",quantity:"2 cups"},{name:"Chicken Broth",quantity:"2 cups"},{name:"Fire Roasted Tomatoes",quantity:"1 can"},{name:"Boursin Cheese",quantity:"1 pkg"}] },
  { name: "Lasagna Soup", url: "", category: "Soup", ingredients: [{name:"Onion",quantity:"1"},{name:"Ricotta",quantity:"1 cup"},{name:"Parmesan",quantity:"1/2 cup"},{name:"Mozzarella",quantity:"1 cup"},{name:"Thyme",quantity:""},{name:"Sage",quantity:""},{name:"Rosemary",quantity:""},{name:"Ground Sausage",quantity:"1 lb"},{name:"Jarlic",quantity:"2 tbsp"},{name:"Tomato Paste",quantity:"2 tbsp"},{name:"Calabrian Chili Peppers",quantity:""},{name:"Chicken Bouillon",quantity:"2"},{name:"Tomato Sauce",quantity:"1 can"},{name:"Heavy Cream",quantity:"1/2 cup"},{name:"Noodles",quantity:"8 oz"}] },
  { name: "Pasta & Meatballs", url: "", category: "Pasta", ingredients: [{name:"Pasta",quantity:"1 lb"},{name:"Meatballs",quantity:""},{name:"Ground Sausage",quantity:"1 lb"}] },
  { name: "Pepper Jack Soup", url: "", category: "Soup", ingredients: [{name:"Onion",quantity:"1"},{name:"Peppers",quantity:""},{name:"Pepper Jack Cheese",quantity:"2 cups"},{name:"Butter",quantity:"2 tbsp"},{name:"Jarlic",quantity:"2 tbsp"},{name:"Small Potatoes",quantity:""},{name:"Flour",quantity:"2 tbsp"},{name:"White Wine",quantity:"1/2 cup"},{name:"Chicken Broth",quantity:"4 cups"},{name:"Ground Sausage",quantity:"1 lb"},{name:"Heavy Cream",quantity:"1 cup"},{name:"White Pepper",quantity:"1 tsp"},{name:"Cornstarch",quantity:"2 tbsp"}] },
  { name: "Quesadillas", url: "", category: "Chicken", ingredients: [{name:"Tortilla Shells",quantity:""},{name:"Shredded Cheddar",quantity:"2 cups"},{name:"Butter",quantity:"2 tbsp"},{name:"Chicken",quantity:"1 lb"}] },
  { name: "Steak & Potatoes", url: "", category: "Steak", ingredients: [] },
  { name: "Steak Bowls", url: "", category: "Steak", ingredients: [{name:"Ribeye Steak",quantity:"1 lb"},{name:"Rice",quantity:"2 cups"},{name:"Queso Fresco",quantity:""},{name:"Balsamic Vinaigrette",quantity:""},{name:"Lime Chips",quantity:""}] },
  { name: "Stir Fry - Chicken", url: "https://natashaskitchen.com/chicken-stir-fry-recipe/", category: "Chicken", ingredients: [{name:"Chicken",quantity:"1.5 lbs"},{name:"Green Beans",quantity:""},{name:"Broccoli",quantity:""},{name:"Carrots",quantity:""},{name:"Peppers",quantity:""},{name:"Onion",quantity:"1"},{name:"Garlic Cloves",quantity:"3 cloves"},{name:"Chicken Broth",quantity:"1/4 cup"},{name:"Soy Sauce",quantity:"3 tbsp"},{name:"Honey",quantity:"2 tbsp"},{name:"Corn Starch",quantity:"1 tbsp"}] },
  { name: "Stir Fry - Steak", url: "https://natashaskitchen.com/chicken-stir-fry-recipe/", category: "Steak", ingredients: [{name:"Steak",quantity:"1.5 lbs"},{name:"Green Beans",quantity:""},{name:"Broccoli",quantity:""},{name:"Carrots",quantity:""},{name:"Peppers",quantity:""},{name:"Onion",quantity:"1"},{name:"Garlic Cloves",quantity:"3 cloves"},{name:"Beef Broth",quantity:"1/4 cup"},{name:"Soy Sauce",quantity:"3 tbsp"},{name:"Honey",quantity:"2 tbsp"},{name:"Corn Starch",quantity:"1 tbsp"}] },
  { name: "Tortellini Soup", url: "https://www.smalltownwoman.com/wprm_print/sausage-tortellini-soup-recipe", category: "Soup", ingredients: [{name:"Ground Sausage",quantity:"1 lb"},{name:"Onion",quantity:"1"},{name:"Minced Garlic",quantity:"3 cloves"},{name:"Basil",quantity:""},{name:"Oregano",quantity:""},{name:"Parsley",quantity:""},{name:"Thyme",quantity:""},{name:"Red Pepper Flakes",quantity:"1 tsp"},{name:"Beef Broth",quantity:"4 cups"},{name:"Tomato Paste",quantity:"2 tbsp"},{name:"Fire Roasted Tomatoes",quantity:"1 can"},{name:"Chicken Broth",quantity:"2 cups"},{name:"Cheese Tortellini",quantity:"9 oz"},{name:"Spinach",quantity:"2 cups"}] },
  { name: "Italian Wedding Soup", url: "", category: "Soup", ingredients: [{name:"Ground Beef",quantity:"1 lb"},{name:"Spicy Sausage",quantity:"1/2 lb"},{name:"Breadcrumbs",quantity:"1/2 cup"},{name:"Egg",quantity:"1"},{name:"Parmesan",quantity:"1/2 cup"},{name:"Parsley",quantity:""},{name:"Garlic Powder",quantity:"1 tsp"},{name:"Onion Powder",quantity:"1 tsp"},{name:"Salt",quantity:"1 tsp"},{name:"Black Pepper",quantity:"1 tsp"},{name:"Paprika",quantity:"1 tsp"},{name:"Italian Seasoning",quantity:"1 tsp"},{name:"Calabrian Peppers",quantity:""},{name:"Avocado Oil",quantity:"2 tbsp"},{name:"Onion",quantity:"1"},{name:"Celery",quantity:""},{name:"Carrots",quantity:""},{name:"Garlic Cloves",quantity:"3 cloves"},{name:"White Wine",quantity:"1/2 cup"},{name:"Chicken Broth",quantity:"6 cups"},{name:"Orzo",quantity:"1 cup"},{name:"Spinach",quantity:"2 cups"}] },
]

export const SEED_EXTRAS = [
  "Little Potatoes","Cereal","Breakfast Crackers","Bagels","Chicken Nugs","Oatmilk",
  "Cold Foam","Bread","Ham","Salami","Keifer","Chocolate Chips","Toilet Paper","Paper Plates (Small)",
]
